---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq
  - ln -s ansible-role-aws ../aplyca.AWS

install:
  # Install Ansible.
  - sudo pip install -r build/requirements.txt

script:
  - tests/tests.sh

notifications:
  email: false
