---
- name: Provision AWS web server
  hosts: all
  roles:
    - { role: Aplyca.AWS, tags: ["aws"] }
  post_tasks:
    - name: Test if AWS CLI is installed
      become: yes
      shell: "aws --version"
      register: result
      failed_when: "'aws-cli' not in result.stdout"
    - name: Test if AWS CloudWatch Logs agent is present and running
      become: yes
      shell: "service awslogs status"
      register: result
      failed_when: "'active (running)' not in result.stdout"
