---
- debug: var=aws verbosity=1
  tags: vars

- name: Make sure AWS CLI is present
  become: yes
  apt:
      name: awscli
      state: present
      update_cache: yes
      cache_valid_time: 86400

- name: Install AWS CloudWatch Logs agent
  become: yes
  apt:
      deb: "{{ item }}"
      state: present
      force: yes
  with_items:
      - https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb
      #- https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/debian_amd64/amazon-ssm-agent.deb

- name: Configure AWS CloudWatch agent
  become: yes
  shell: "amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -c ssm:{{ aws.cloudwatch.configuration_name }} -s"
  args:
      chdir: "/opt/aws/amazon-cloudwatch-agent/bin/"
  tags: cloudwatch

- name: Add AWS credentials
  block:
      - name: Make sure the AWS-CLI directory is present
        file:
            dest: "~/.aws/"
            state: directory

      - name: Use AWS Credentials
        template:
            src: credentials.j2
            dest: ~/.aws/credentials
            mode: 0600

      - name: Use AWS Config
        template:
            src: config.j2
            dest: ~/.aws/config
            mode: 0600
  when: aws.credentials

- name: Install AWS CodeDeploy Agent
  block:
      - name: Download AWS CodeDeploy Agent installer
        get_url:
            url: "{{ aws.codedeploy.agent_url }}"
            dest: /tmp/install
            mode: 0755

      - name: Install AWS CodeDeploy Agent
        become: yes
        shell: "/tmp/install auto"
        args:
            creates: /etc/init.d/codedeploy-agent
        notify: start codedeploy-agent
  when: aws.codedeploy.enabled
