---
- name: Make sure Python pip is present using apt
  sudo: yes
  apt: 
    name: python-pip
    state: present
    
- name: make sure AWS CLI is present
  sudo: yes
  pip: 
    name: awscli    

- name: Download AWS Log installer
  get_url:
    url: "{{ aws_log_agent_url }}"
    dest: /tmp/awslogs-agent-setup.py

- name: Install AWS Logs deamon
  sudo: yes
  shell: /usr/bin/python /tmp/awslogs-agent-setup.py -n -r {{ aws_region }} -c {{ item }}
  with_items:
    - /var/log/syslog

- name: Make sure the AWS Logs config is present
  sudo: yes
  template:
    src: awslogs.conf.j2
    dest: /var/awslogs/etc/awslogs.conf

- name: Make sure the AWS-CLI directory is present
  sudo: yes
  file:
    dest: "~/.aws/"
    state: directory

- name: Use AWS Credentials
  sudo: yes
  template:
    src: awscredentials.j2
    dest: ~/.aws/credentials

- name: Use AWS Config
  sudo: yes
  template:
    src: awsconfigure.j2
    dest: ~/.aws/config