---
- name: Make sure Python pip is present using apt
  sudo: yes
  apt: 
    name: python-pip
    state: present
    
- name: make sure AWS CLI is present
  sudo: yes
  pip: 
    name: awscli    

- name: Download AWS CloudWatch Logs installer
  get_url:
    url: "{{ aws['cloudwatch']['agent_url'] }}"
    dest: /tmp/awslogs-agent-setup.py

- name: Install AWS CloudWatch Logs deamon
  sudo: yes
  shell: "/usr/bin/python /tmp/awslogs-agent-setup.py --non-interactive --region {{ aws['cloudwatch']['region'] }} -c /var/awslogs/etc/aws.conf"

- name: Make sure the AWS CloudWatch Logs config is present
  sudo: yes
  template:
    src: awslogs.conf.j2
    dest: /var/awslogs/etc/awslogs.conf