---
- name: Download AWS Log installer
  get_url:
    url: "{{ aws_log_agent_url }}"
    dest: /tmp/awslogs-agent-setup.py

- name: Install AWS Logs deamon
  sudo: yes
  shell: /usr/bin/python /tmp/awslogs-agent-setup.py -n -r {{ aws_region }} -c {{ item }}
  with_items:
    - /var/log/syslog

- name: Make sure the AWS Logs config is present
  sudo: yes
  template:
    src: awslogs.conf.j2
    dest: /var/awslogs/etc/awslogs.conf

- name: Download PIP
  sudo: yes
  get_url:
    url: "{{ python_pip }}"
    dest: "{{ python_pip_file }}"
    
- name: Install PIP
  sudo: yes
  command: python2.7 "{{ python_pip_file }}"
    
- name: Install AWS Cli
  sudo: yes
  pip: name=awscli