Vagrant.configure(2) do |config|
  config.vm.define "aws.vagrant", primary: true, autostart: true do |config_machine|
      #Assigning a provider
      config_machine.vm.provider :virtualbox do |virtualbox, override|
          virtualbox.name = "Vagrant AWS"
		  #override.vm.box = "chef/centos-7.0"
		  override.vm.box = "ubuntu/trusty64"
          #override.vm.box = "hashicorp/precise64"
      end

      # Asinging a provisioner
      config_machine.vm.provision :ansible, run: "always" do |provisioner|
          provisioner.playbook = "playbook.yml"
          provisioner.extra_vars = "custom_vars.yml" if File.file?("custom_vars.yml")
      end
  end
end
