---
- name: restart awslogs
  become: yes
  service:
    name: awslogs
    state: restarted
    enabled: yes

- name: start codedeploy-agent
  become: yes
  service:
    name: codedeploy-agent
    state: start
    enabled: yes
